baseURL = "https://saultcollege-git-basics.netlify.com"
languageCode = "en-us"
title = "Git Basics"
theme = ["hugo-book"]

paginate = 1

[markup.goldmark.renderer] 
    unsafe = true 

[markup.highlight]
    style = "arduino-light" # "xcode"

[Params]
    menu_style = "slide-menu"